### ISSUE TITLE
Unable to use Schedule app.

### ISSUE THREAD

**Issue by quain24** [ardalis/pluralsight-ddd-fundamentals#36]
After initial docker setup, with all containers running, when firing up the `http://localhost:5100/`
I'm welcomed with following exception in browser's console:

```C#
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: String '09/23/2030 00:00:00 -04:00' was not recognized as a valid DateTime.
System.FormatException: String '09/23/2030 00:00:00 -04:00' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at System.Convert.ToDateTime(String value)
   at FrontDesk.Blazor.Services.ConfigurationService.ReadAsync()
   at FrontDesk.Blazor.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

In addition:
![obraz](https://user-images.githubusercontent.com/25936793/139423213-d2cb672d-8453-4777-a11f-70ac4db488d3.png)

**Comment by ardalis** [comment]
Are you able to build locally? Docker is an option, and usually an easier one, but not the only one.

**Comment by quain24** [comment]
Yes, with suggested rabbit-mq container spun up I am able to run FrontDesk.Blazor from VS.
My main concern is that I wanted to see all of this working as one, as presented in Your Pluralsight course.

**Comment by ardalis** [comment]
You can do that by just having multiple visual studio instances (or terminals) running, and run each of the apps on their own ports. The table in the README shows the ports that should be in use when you do this yourself vs. in docker. When I'm working with it locally and troubleshooting, debugging, or even developing this is how I run it.

**Comment by ardalis** [comment]
I think this is now fixed - let me know if it's still an issue.
