### ISSUE TITLE
Appointments not showing in calendar 

### ISSUE THREAD

**Issue by kenrazo** [ardalis/pluralsight-ddd-fundamentals#57]
I tried to set it up in docker and in visual studio. The app is running but the appointments are not showing in the calendar even though I created a new one.,

**Comment by Rahtgaz** [comment]
Same problem when setting up the development environment for Visual Studio as explained in the readme-md file.
The FrontDesk.Blazor client app shows a yellow banner with a java handled exception, and does not show the appointments calendar.

**Comment by ardalis** [comment]
I think there may be some timezone issues associated with the default seeded appointments. I'm not sure why anyone would be seeing java errors - there's no java anywhere in the application. Do you mean JavaScript?

**Comment by Rahtgaz** [comment]
Yeah. I mean JavaScript. Don't even ask... 👎 

So, the issue should be resolved in https://github.com/ardalis/pluralsight-ddd-fundamentals/pull/59 which replaces invariant culture specifier with the current culture of the client.

**Comment by Rahtgaz** [comment]
What I don't understand is that InvariantCulture is definitely an error in there and needs to be fixed. The following throws an exception:

```
var foo = new DateTimeOffset(2030, 9, 23, 0, 0, 0, new TimeSpan(-4, 0, 0));
var bar = DateTimeOffset.Parse(foo.ToString(), CultureInfo.CurrentCulture);
```

But when I change it to current culture, I still get the unhandled exception.
![image](https://user-images.githubusercontent.com/10880397/233452388-e1dfbade-0065-4111-8562-4f59add77790.png)

**Comment by Rahtgaz** [comment]
@kenrazo #60 should fix it for you.
