### ISSUE TITLE
Error	NU1101	Unable to find package Pluralsight.DDD.Deps. No packages exist with this id in source(s)

### ISSUE THREAD

**Issue by iarunpaul** [ardalis/pluralsight-ddd-fundamentals#65]
During the build one of the custom public Nuget package restore fails:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Pluralsight.DDD.Deps. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	FrontDesk.Blazor.Host	C:\Users\ArunPaul\source\repos\DDD\pluralsight-ddd-fundamentals\FrontDesk\src\FrontDesk.Blazor.Host\FrontDesk.Blazor.Host.csproj	1	

```
When I checked the Nuget repository, it doesn't exist, but the closest package available is 
`PluralsightDdd.SharedKernel`.
I tried for building the application with the `PluralsightDdd.SharedKernel` package but it never builds.

Can someone suggest a solution?

**Comment by GraemeWellington** [comment]
In Visual Studio in FrontDesk solution right click on the solution and select Manage Nuget Packages for Solution.
In the far right click on the Options coga nd then Add a Package Source - from the suggested youtube video in the README.md enter DDDFundamentals and then click the button with 3 dots and navigate to : [from the solution main folder] 
/FrontDesk/src/FrontDesk.Blazor/deps/Pluralsight.DDD.Deps/Pluralsight.DDD.Deps.1.0.0.nupkg - select and OK. You will then have the DDDFundamentals in the Package source pulldown.

**Comment by iarunpaul** [comment]
> In Visual Studio in FrontDesk solution right click on the solution and select Manage Nuget Packages for Solution. In the far right click on the Options cog and then Add a Package Source (from the suggested youtube video in the README.md) use the name DDDFundamentals and then click the button with 3 dots and navigate to : [from the solution main folder] /FrontDesk/src/FrontDesk.Blazor/deps/Pluralsight.DDD.Deps/Pluralsight.DDD.Deps.1.0.0.nupkg - select and OK. You will then have the DDDFundamentals in the Package source pulldown.

Thank you! It resolved the issue.

**Comment by htsilvakt041** [comment]
For anyone who use Rider (You don't like VS something).
Tools -> Nuget -> Show NuGet sources.
Then add a new source by clicking the +, then choose any name, but the URL will be the absolute path **to the folder that contains** the Pluralsight.DDD.Deps.1.0.0.nupkg file. For example: 
URL: /Users/silva/Downloads/fundamentals-domain-driven-design/pluralsight-ddd-fundamentals/FrontDesk/src/FrontDesk.Blazor/deps/Pluralsight.DDD.Deps/

Then add it, and you will be good.
