### ISSUE TITLE
Ardalis Endpoints problem in Read.cs of DDD Fundamentals Course

### ISSUE THREAD

**Issue by IrisPeter** [ardalis/pluralsight-ddd-fundamentals#66]
I've been going through the FrontDesk project updating it to the latest Nuget packages.

Some changes are required in Read.cs to make the project Frontdesk.Api build, one of these is in Read.cs

I'm able to follow some of the 4.x upgrade steps to fix the problems, these are listed as the two main changes.

The final problem is confusing as the HandleAsync method in Read.cs looks like the example.  I have changed WithResponse<sting> to WithResult<string>

However I am getting a compiler error on the following code:

```cs
public override async Task<ActionResult<string>> HandleAsync(CancellationToken cancellationToken)
{
  return Ok(new OfficeSettings().TestDate.ToString(CultureInfo.InvariantCulture));
}
```
I had assumed that the `WithResult<string>` would have been the line that made the above code valid!

What is the correct fix here?

**Comment by ardalis** [comment]
What is the error you're getting? I don't see a `WithResult<string>` anywhere in your code, either (or WithResponse for that matter). Can you show more code and the error you're getting? Screenshots work with copy/paste too if that's easier.

**Comment by IrisPeter** [comment]
Screenshot with the error:

![image](https://github.com/ardalis/pluralsight-ddd-fundamentals/assets/47663858/afd94f72-15e0-496d-9c0b-07efef648a01)
CS0115 'Read.HandleAsync(CancellationToken)': no suitable method found to override

**Comment by canro91** [comment]
@ardalis After PR #69, we can close this one too
