### ISSUE TITLE
Switch from Ardalis.ApiEndpoints to FastEndpoints

### ISSUE THREAD

**Issue by ardalis** [ardalis/pluralsight-ddd-fundamentals#71]
Replace web APIs that are now using Ardalis.ApiEndpoints package and use FastEndpoints package instead.

Modify Program.cs files so they no longer load Controllers at all (for API projects that no longer need them). If we need server-rendered pages use RazorPages for that.

When this is done there should be no more Controllers or Views folders in any projects (if there were any), and the Program.cs files should mainly just have FastEndpoints wired up (and RazorPages if needed)

**Comment by canro91** [comment]
@ardalis I'm taking this one first
