### ISSUE TITLE
Consider MassTransit for RabbitMQ messaging

### ISSUE THREAD

**Issue by ardalis** [ardalis/pluralsight-ddd-fundamentals#73]
I've found that setting up and working with MassTransit is much simpler than working with RabbitMQ directly.

See:
https://ardalis.com/introduction-to-masstransit-csharp-guide/

Consider adding a dependency on MT and using it to wrap all access to RMQ and updating all code and configuration accordingly. If there are reasons this won't work describe them in comments here or in associated PR.

**Comment by lloydkevin** [comment]
@ardalis a couple of questions/considerations:
- Does switching to MassTransit cause a large discrepancy between the repo and the Pluralsight video content? Wouldn't want to have to re-record content, I suppose
- Can the contracts be in a shared project that all modules link to (easier) or do you want these deployed using nuget like the shared kernel?

**Comment by ardalis** [comment]
1. Not sure but I don't think I dove into the weeds in the course. In any case we are updating the course right now so if I need to it I can do so.
2. Contracts can be simply copied for now (as in, put the same .cs file on both sides of the conversation) if that works.
