### ISSUE TITLE
Logger in ClinicManagementClientConsumer.cs 

### ISSUE THREAD

**Issue by KhalilLazhar** [ardalis/pluralsight-ddd-fundamentals#92]
Hello,

The logger inside ClinicManagementClientConsumer.cs in FrontDesk\src\FrontDesk.Api\MessageHandlers  is defined with ClinicManagementDoctorConsumer .
I think we need to change it to ClinicManagementClientConsumer.

<img width="824" alt="Capture d’écran 2024-10-27 190550" src="https://github.com/user-attachments/assets/ddbbc031-f764-4854-bdb5-a89a2f65cc9e">

**Comment by ardalis** [comment]
Good catch!
